---
- hosts: all

  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/system.yml
      tags:
        - system
        - up
    - import_tasks: tasks/homebrew-work.yml
      tags:
        - brew
        - up
    - import_tasks: tasks/node.yml
      tags:
        - node
        - up
    - import_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - up
    - import_tasks: tasks/fonts.yml
      tags:
        - fonts
        - up
