---
- name: read /etc/shells
  register: etc_shells
  shell: cat /etc/shells

- name: append homebrew bash shell to /etc/shells
  shell: echo "/opt/homebrew/bin/bash" | sudo tee -a /etc/shells
  when: "'/opt/homebrew/bin/bash' not in etc_shells.stdout"

- name: get the current shell
  shell: echo $SHELL
  register: current_shell

- name: default to the homebrew bash shell
  shell: chsh -s /opt/homebrew/bin/bash
  when: current_shell.stdout != "/opt/homebrew/bin/bash"

- name: create ~/.bash
  file:
    path: ~/.bash
    state: directory

- name: download git-completion.bash
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: ~/.bash/git-completion.bash

- name: create ~/dev
  file:
    path: ~/dev
    state: directory

- name: clone dotfiles repo
  git:
    repo: git@github.com:bmealhouse/dotfiles.git
    dest: ~/dev/dotfiles

- name: create a symbolic link for .bashrc
  file:
    src: ~/dev/dotfiles/bash/.bashrc
    dest: ~/.bashrc
    state: link

- name: create a symbolic link for alacritty
  file:
    src: ~/dev/dotfiles/alacritty
    dest: ~/.config/alacritty
    state: link
# - name: clone nvchad repo
#   git:
#     repo: https://github.com/NvChad/NvChad
#     dest: ~/.config/nvim
#     depth: 1

# - name: create a symbolic link for neovim
#   file:
#     src: ~/dev/dotfiles/nvim/lua/custom
#     dest: ~/.config/nvim/lua/custom
#     state: link

# - name: create a symbolic link for neovim
#   file:
#     src: ~/dev/dotfiles/nvim
#     dest: ~/.config/nvim
#     state: link
