---
- name: create ~/dev
  file:
    path: ~/dev
    state: directory

- name: clone dotfiles repo
  git:
    repo: git@github.com:bmealhouse/dotfiles.git
    dest: ~/dev/dotfiles

- name: create a symbolic link for .zshrc
  file:
    src: ~/dev/dotfiles/zsh/.zshrc
    dest: ~/.zshrc
    state: link

- name: create a symbolic link for alacritty
  file:
    src: ~/dev/dotfiles/alacritty
    dest: ~/.config/alacritty
    state: link

- name: clone nvchad repo
  git:
    repo: https://github.com/NvChad/NvChad
    dest: ~/.config/nvim
    depth: 1

- name: create a symbolic link for neovim
  file:
    src: ~/dev/dotfiles/nvim/lua/custom
    dest: ~/.config/nvim/lua/custom
    state: link
