---
- name: check if homebrew is installed
  register: homebrew_path
  stat:
    path: /opt/homebrew

- name: install homebrew
  script: ../install-homebrew.sh
  when: not homebrew_path.stat.exists

- name: add homebrew to PATH
  shell: |
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  when: not homebrew_path.stat.exists

- name: tap homebrew repositories
  community.general.homebrew_tap:
    name:
      - aws/tap
      - beeftornado/rmtree
      - homebrew/cask
      - homebrew/cask-fonts
      - homebrew/cask-versions
      - planetscale/tap
    state: present
  tags:
    - up

- name: install homebrew formulae
  community.general.homebrew:
    name:
      - aws-sam-cli
      - awscli
      - bat
      - go
      - jq
      - neovim
      - pscale
      - ripgrep
      - starship
      - volta
    state: latest
    update_homebrew: true
  tags:
    - up

- name: install homebrew casks
  community.general.homebrew_cask:
    name:
      - 1password
      - alacritty
      - amazon-workspaces
      - appcleaner
      - arc
      - authy
      # - betterdisplay
      - google-chrome
      - grammarly-desktop
      - iina
      - perimeter81
      - postman
      - raycast
      - reader
      - sequel-ace
      - slack
      - slite
      - temurin8
      - visual-studio-code
      - warp
    state: latest
    update_homebrew: true
  tags:
    - up

- name: install homebrew fonts
  community.general.homebrew_cask:
    name:
      - font-agave-nerd-font
      - font-arimo-nerd-font
      - font-aurulent-sans-mono-nerd-font
      - font-bitstream-vera-sans-mono-nerd-font
      - font-caskaydia-cove-nerd-font
      - font-comic-shanns-mono-nerd-font
      - font-daddy-time-mono-nerd-font
      - font-droid-sans-mono-nerd-font
      - font-fira-code-nerd-font
      - font-go-mono-nerd-font
      - font-hack-nerd-font
      - font-heavy-data-nerd-font
      - font-im-writing-nerd-font
      - font-inconsolata-lgc-nerd-font
      - font-iosevka-nerd-font
      - font-jetbrains-mono-nerd-font
      - font-liberation-nerd-font
      - font-meslo-lg-nerd-font
      - font-monofur-nerd-font
      - font-mononoki-nerd-font
      - font-open-dyslexic-nerd-font
      - font-profont-nerd-font
      - font-roboto-mono-nerd-font
      - font-shure-tech-mono-nerd-font
      - font-symbols-only-nerd-font
      - font-tinos-nerd-font
      - font-ubuntu-nerd-font
      - font-victor-mono-nerd-font
  tags:
    - up
