---
- name: check if homebrew is installed
  register: homebrew_path
  stat:
    path: /opt/homebrew

- name: install homebrew
  script: ../install-homebrew.sh
  when: not homebrew_path.stat.exists

- name: add homebrew to PATH
  shell: |
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  when: not homebrew_path.stat.exists

- name: tap homebrew/cask repositories
  community.general.homebrew_tap:
    name:
      - beeftornado/rmtree
      - homebrew/cask
      - homebrew/cask-versions
    state: present
  tags:
    - up

- name: install homebrew formulae
  community.general.homebrew:
    name:
      - bat
      - exiftool
      - go
      - jq
      - neovim
      - ripgrep
      - volta
      - youtube-dl
    state: latest
    update_homebrew: true
  tags:
    - up

- name: install homebrew casks
  community.general.homebrew_cask:
    name:
      - 1password
      - alacritty
      - appcleaner
      - figma
      - grammarly-desktop
      - iina
      - ilok-license-manager
      - ngrok
      - raycast
      - steam
      - visual-studio-code
      - vlc
      - warp
    state: latest
    update_homebrew: true
  tags:
    - up

- name: check if arc is installed
  register: arc_path
  stat:
    path: /Applications/Arc.app
  tags:
    - up

- name: install arc
  community.general.homebrew_cask:
    name:
      - arc
    state: latest
    update_homebrew: true
  when: not arc_path.stat.exists
  tags:
    - up
